Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/BlockComments:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
